-- FTAE dev-project seed.
-- Generated by concatenating supabase/migrations/*.sql in order.
-- Paste into the SQL editor of a fresh Supabase project.


-- ============================================================
-- 20260414000000_initial_schema.sql
-- ============================================================

-- =============================================================================
-- FTAE Initial Schema
-- Free Trade Art Exchange — Production Database
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
create extension if not exists "pgcrypto";   -- gen_random_uuid()
create extension if not exists "citext";     -- case-insensitive text for email

-- ---------------------------------------------------------------------------
-- Enum Types
-- ---------------------------------------------------------------------------

create type user_role as enum ('member', 'admin', 'super_admin');

create type user_ip_event as enum ('signup', 'login', 'profile_update');

create type social_platform as enum (
  'instagram', 'facebook', 'x', 'tiktok', 'youtube', 'pinterest', 'linkedin'
);

create type artwork_condition as enum (
  'excellent', 'good', 'fair', 'needs_restoration'
);

create type dimension_unit as enum ('in', 'cm');

create type artwork_photo_type as enum ('front', 'back', 'detail', 'shipping');

create type credit_type as enum ('founding_member', 'referral_bonus');

create type notification_type as enum (
  'profile_nudge',
  'referral_joined',
  'referral_completed',
  'trade_proposal',
  'trade_match',
  'system'
);

create type admin_action_type as enum (
  'deactivate', 'activate', 'studio_verify', 'identity_verify'
);

create type trade_status as enum (
  'proposed',
  'countered',
  'matched',
  'initiator_shipped',
  'recipient_shipped',
  'initiator_confirmed',
  'recipient_confirmed',
  'completed',
  'cancelled',
  'disputed'
);

create type shipping_terms as enum (
  'each_pays_own',
  'initiator_pays_all',
  'recipient_pays_all',
  'split',
  'custom'
);

create type trade_side as enum ('initiator', 'recipient');

create type proposal_status as enum ('pending', 'accepted', 'declined', 'countered');

-- ---------------------------------------------------------------------------
-- Timestamp trigger
-- Sets updated_at automatically on any row update.
-- ---------------------------------------------------------------------------

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- USERS
-- ---------------------------------------------------------------------------

create table users (
  id                      uuid primary key default gen_random_uuid(),
  email                   citext unique not null,
  name                    varchar,
  location_city           varchar,
  location_region         varchar,
  location_country        varchar,
  bio                     varchar(160),
  avatar_url              text,
  website_url             text,
  social_platform         social_platform,
  social_handle           varchar,
  role                    user_role not null default 'member',
  is_active               boolean not null default true,
  is_founding_member      boolean not null default false,
  identity_verified       boolean not null default false,
  studio_verified         boolean not null default false,
  profile_completion_pct  integer not null default 0 check (profile_completion_pct between 0 and 100),
  referral_code           varchar unique,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create trigger users_updated_at
  before update on users
  for each row execute function set_updated_at();

create index users_role_idx on users (role);
create index users_is_active_idx on users (is_active);
create index users_is_founding_member_idx on users (is_founding_member);
create index users_referral_code_idx on users (referral_code);

-- ---------------------------------------------------------------------------
-- USER_IPS
-- ---------------------------------------------------------------------------

create table user_ips (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references users (id) on delete cascade,
  ip_address  inet not null,
  event_type  user_ip_event not null,
  created_at  timestamptz not null default now()
);

create index user_ips_user_id_idx on user_ips (user_id);
create index user_ips_ip_address_idx on user_ips (ip_address);
create index user_ips_created_at_idx on user_ips (created_at);

-- ---------------------------------------------------------------------------
-- MEDIUMS
-- ---------------------------------------------------------------------------

create table mediums (
  id          uuid primary key default gen_random_uuid(),
  name        varchar not null unique,
  sort_order  integer not null default 0
);

create index mediums_sort_order_idx on mediums (sort_order);

-- Seed canonical medium values
insert into mediums (name, sort_order) values
  ('Oil',             1),
  ('Acrylic',         2),
  ('Watercolor',      3),
  ('Gouache',         4),
  ('Pastel',          5),
  ('Charcoal',        6),
  ('Graphite',        7),
  ('Ink',             8),
  ('Printmaking',     9),
  ('Photography',    10),
  ('Sculpture',      11),
  ('Ceramic',        12),
  ('Textile',        13),
  ('Mixed Media',    14),
  ('Digital',        15),
  ('Collage',        16),
  ('Drawing',        17),
  ('Encaustic',      18),
  ('Resin',          19),
  ('Other',          99);

-- ---------------------------------------------------------------------------
-- USER_MEDIUMS
-- ---------------------------------------------------------------------------

create table user_mediums (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references users (id) on delete cascade,
  medium_id   uuid not null references mediums (id) on delete cascade,
  unique (user_id, medium_id)
);

create index user_mediums_user_id_idx on user_mediums (user_id);
create index user_mediums_medium_id_idx on user_mediums (medium_id);

-- ---------------------------------------------------------------------------
-- ARTWORKS
-- ---------------------------------------------------------------------------

create table artworks (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references users (id) on delete cascade,
  title               varchar,
  year                integer check (year between 1000 and extract(year from now())::integer + 1),
  medium              varchar,
  height              decimal(8, 2),
  width               decimal(8, 2),
  depth               decimal(8, 2),
  dimension_unit      dimension_unit not null default 'in',
  condition           artwork_condition,
  declared_value      decimal(10, 2),
  artist_statement    text,
  is_trade_available  boolean not null default true,
  is_active           boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create trigger artworks_updated_at
  before update on artworks
  for each row execute function set_updated_at();

create index artworks_user_id_idx on artworks (user_id);
create index artworks_is_trade_available_idx on artworks (is_trade_available);
create index artworks_is_active_idx on artworks (is_active);

-- ---------------------------------------------------------------------------
-- ARTWORK_PHOTOS
-- ---------------------------------------------------------------------------

create table artwork_photos (
  id          uuid primary key default gen_random_uuid(),
  artwork_id  uuid not null references artworks (id) on delete cascade,
  url         text not null,
  photo_type  artwork_photo_type not null default 'front',
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);

create index artwork_photos_artwork_id_idx on artwork_photos (artwork_id, sort_order);

-- ---------------------------------------------------------------------------
-- FOLLOWS
-- ---------------------------------------------------------------------------

create table follows (
  id            uuid primary key default gen_random_uuid(),
  follower_id   uuid not null references users (id) on delete cascade,
  following_id  uuid not null references users (id) on delete cascade,
  is_queued     boolean not null default false,
  created_at    timestamptz not null default now(),
  unique (follower_id, following_id),
  check (follower_id <> following_id)
);

create index follows_follower_id_idx on follows (follower_id);
create index follows_following_id_idx on follows (following_id);
create index follows_is_queued_idx on follows (is_queued) where is_queued = true;

-- ---------------------------------------------------------------------------
-- REFERRALS
-- ---------------------------------------------------------------------------

create table referrals (
  id                      uuid primary key default gen_random_uuid(),
  referrer_user_id        uuid not null references users (id) on delete cascade,
  referred_user_id        uuid references users (id) on delete set null,
  referral_code           varchar not null,
  clicked_at              timestamptz not null default now(),
  signup_completed_at     timestamptz,
  profile_completed_at    timestamptz,
  credit_issued           boolean not null default false,
  created_at              timestamptz not null default now()
);

create index referrals_referrer_user_id_idx on referrals (referrer_user_id);
create index referrals_referred_user_id_idx on referrals (referred_user_id);
create index referrals_referral_code_idx on referrals (referral_code);
create index referrals_credit_issued_idx on referrals (credit_issued) where credit_issued = false;

-- ---------------------------------------------------------------------------
-- MEMBERSHIP_CREDITS
-- Append-only ledger. Never update or delete rows.
-- Total free months = sum(months_credited) for a user_id.
-- Credit types and their caps (enforced by trigger in 000002, updated in 000003):
--   founding_member:  issued exactly once per user, months_credited must be 3
--   referral_bonus:   sum of months_credited per user may not exceed 3
--   trade_completion: no cap — one row per completed trade, unlimited accrual
-- ---------------------------------------------------------------------------

create table membership_credits (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references users (id) on delete cascade,
  credit_type         credit_type not null,
  months_credited     integer not null check (months_credited > 0),
  source_referral_id  uuid references referrals (id) on delete set null,
  note                text,
  created_at          timestamptz not null default now()
);

create index membership_credits_user_id_idx on membership_credits (user_id);
create index membership_credits_credit_type_idx on membership_credits (credit_type);

-- ---------------------------------------------------------------------------
-- NOTIFICATIONS
-- ---------------------------------------------------------------------------

create table notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references users (id) on delete cascade,
  type        notification_type not null,
  message     text not null,
  is_read     boolean not null default false,
  action_url  text,
  created_at  timestamptz not null default now()
);

create index notifications_user_id_idx on notifications (user_id, created_at desc);
create index notifications_unread_idx on notifications (user_id) where is_read = false;

-- ---------------------------------------------------------------------------
-- ADMIN_ACTIONS
-- Append-only audit log. Never update or delete rows.
-- ---------------------------------------------------------------------------

create table admin_actions (
  id               uuid primary key default gen_random_uuid(),
  admin_user_id    uuid not null references users (id) on delete cascade,
  target_user_id   uuid not null references users (id) on delete cascade,
  action_type      admin_action_type not null,
  reason           text,
  created_at       timestamptz not null default now()
);

create index admin_actions_admin_user_id_idx on admin_actions (admin_user_id);
create index admin_actions_target_user_id_idx on admin_actions (target_user_id);

-- ---------------------------------------------------------------------------
-- TRADES
-- ---------------------------------------------------------------------------

create table trades (
  id                        uuid primary key default gen_random_uuid(),
  initiator_id              uuid not null references users (id) on delete cascade,
  recipient_id              uuid not null references users (id) on delete cascade,
  status                    trade_status not null default 'proposed',
  shipping_terms            shipping_terms,
  shipping_terms_custom     text,
  initiator_tracking        varchar,
  recipient_tracking        varchar,
  initiator_delivered_at    timestamptz,
  recipient_delivered_at    timestamptz,
  obligation_deadline       timestamptz,
  completed_at              timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  check (initiator_id <> recipient_id)
);

create trigger trades_updated_at
  before update on trades
  for each row execute function set_updated_at();

create index trades_initiator_id_idx on trades (initiator_id);
create index trades_recipient_id_idx on trades (recipient_id);
create index trades_status_idx on trades (status);

-- ---------------------------------------------------------------------------
-- TRADE_PACKAGES
-- ---------------------------------------------------------------------------

create table trade_packages (
  id          uuid primary key default gen_random_uuid(),
  trade_id    uuid not null references trades (id) on delete cascade,
  artwork_id  uuid not null references artworks (id) on delete cascade,
  side        trade_side not null,
  created_at  timestamptz not null default now()
);

create index trade_packages_trade_id_idx on trade_packages (trade_id);
create index trade_packages_artwork_id_idx on trade_packages (artwork_id);

-- ---------------------------------------------------------------------------
-- TRADE_PROPOSALS
-- ---------------------------------------------------------------------------

create table trade_proposals (
  id              uuid primary key default gen_random_uuid(),
  trade_id        uuid not null references trades (id) on delete cascade,
  proposed_by     uuid not null references users (id) on delete cascade,
  round           integer not null default 1 check (round >= 1),
  message         text,
  shipping_terms  shipping_terms,
  status          proposal_status not null default 'pending',
  created_at      timestamptz not null default now()
);

create index trade_proposals_trade_id_idx on trade_proposals (trade_id, round);
create index trade_proposals_proposed_by_idx on trade_proposals (proposed_by);

-- ---------------------------------------------------------------------------
-- PROVENANCE_RECORDS
-- Immutable snapshot written at trade completion.
-- record_data captures artwork details, photos, declared value, artist
-- statement, and verified identities of both parties at the moment of trade.
-- ---------------------------------------------------------------------------

create table provenance_records (
  id                      uuid primary key default gen_random_uuid(),
  trade_id                uuid not null references trades (id) on delete cascade,
  artwork_id              uuid not null references artworks (id) on delete cascade,
  owner_user_id           uuid not null references users (id) on delete cascade,
  previous_owner_user_id  uuid not null references users (id) on delete cascade,
  record_data             jsonb not null,
  generated_at            timestamptz not null default now()
);

create index provenance_records_trade_id_idx on provenance_records (trade_id);
create index provenance_records_artwork_id_idx on provenance_records (artwork_id);
create index provenance_records_owner_user_id_idx on provenance_records (owner_user_id);

-- ============================================================
-- 20260414000001_rls_policies.sql
-- ============================================================

-- =============================================================================
-- FTAE Row Level Security Policies
-- Users can only read/write their own data by default.
-- Public profile data is explicitly granted for read.
-- Admin/super_admin bypass is handled via role checks.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Helper function: current user's role
-- ---------------------------------------------------------------------------

create or replace function current_user_role()
returns user_role
language sql
stable
as $$
  select role from users where id = auth.uid()
$$;

-- ---------------------------------------------------------------------------
-- USERS
-- ---------------------------------------------------------------------------

alter table users enable row level security;

-- Anyone can read basic profile data (public profiles)
create policy "users: public read"
  on users for select
  using (is_active = true);

-- Users can update their own row
create policy "users: self update"
  on users for update
  using (id = auth.uid());

-- Admins can update any user row
create policy "users: admin update"
  on users for update
  using (current_user_role() in ('admin', 'super_admin'));

-- New rows are inserted by the auth trigger (service role), not by users directly
-- No insert policy needed for anon/authenticated roles

-- ---------------------------------------------------------------------------
-- USER_IPS
-- ---------------------------------------------------------------------------

alter table user_ips enable row level security;

-- Admins only — users have no business reading IP logs
create policy "user_ips: admin read"
  on user_ips for select
  using (current_user_role() in ('admin', 'super_admin'));

-- Insert via service role (auth trigger) — no user insert policy

-- ---------------------------------------------------------------------------
-- MEDIUMS
-- ---------------------------------------------------------------------------

alter table mediums enable row level security;

-- Public read — everyone can see available mediums
create policy "mediums: public read"
  on mediums for select
  using (true);

-- Admins can manage medium list
create policy "mediums: admin write"
  on mediums for all
  using (current_user_role() in ('admin', 'super_admin'));

-- ---------------------------------------------------------------------------
-- USER_MEDIUMS
-- ---------------------------------------------------------------------------

alter table user_mediums enable row level security;

-- Anyone can read (used for profile display and discovery filters)
create policy "user_mediums: public read"
  on user_mediums for select
  using (true);

-- Users manage their own medium selections
create policy "user_mediums: self write"
  on user_mediums for all
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- ARTWORKS
-- ---------------------------------------------------------------------------

alter table artworks enable row level security;

-- Anyone can read active artworks available for trade
create policy "artworks: public read"
  on artworks for select
  using (is_active = true);

-- Users can read all their own artworks (including inactive)
create policy "artworks: self read all"
  on artworks for select
  using (user_id = auth.uid());

-- Users manage their own artworks
create policy "artworks: self write"
  on artworks for all
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- ARTWORK_PHOTOS
-- ---------------------------------------------------------------------------

alter table artwork_photos enable row level security;

-- Readable if the parent artwork is readable (active, or owned by user)
create policy "artwork_photos: read via artwork"
  on artwork_photos for select
  using (
    exists (
      select 1 from artworks a
      where a.id = artwork_photos.artwork_id
        and (a.is_active = true or a.user_id = auth.uid())
    )
  );

-- Users manage photos for their own artworks
create policy "artwork_photos: self write"
  on artwork_photos for all
  using (
    exists (
      select 1 from artworks a
      where a.id = artwork_photos.artwork_id
        and a.user_id = auth.uid()
    )
  );

-- ---------------------------------------------------------------------------
-- FOLLOWS
-- ---------------------------------------------------------------------------

alter table follows enable row level security;

-- Follow counts are public (for profile display)
create policy "follows: public read"
  on follows for select
  using (true);

-- Users manage their own follows
create policy "follows: self write"
  on follows for all
  using (follower_id = auth.uid());

-- ---------------------------------------------------------------------------
-- REFERRALS
-- ---------------------------------------------------------------------------

alter table referrals enable row level security;

-- Referrers can see their own referral records
create policy "referrals: self read"
  on referrals for select
  using (referrer_user_id = auth.uid());

-- Admins can read all referrals
create policy "referrals: admin read"
  on referrals for select
  using (current_user_role() in ('admin', 'super_admin'));

-- Inserts via service role (application layer writes referral on link click)

-- ---------------------------------------------------------------------------
-- MEMBERSHIP_CREDITS
-- ---------------------------------------------------------------------------

alter table membership_credits enable row level security;

-- Users can read their own credit ledger
create policy "membership_credits: self read"
  on membership_credits for select
  using (user_id = auth.uid());

-- Admins can read all credits
create policy "membership_credits: admin read"
  on membership_credits for select
  using (current_user_role() in ('admin', 'super_admin'));

-- No user insert — credits written by service role only (prevents tampering)

-- ---------------------------------------------------------------------------
-- NOTIFICATIONS
-- ---------------------------------------------------------------------------

alter table notifications enable row level security;

-- Users read their own notifications only
create policy "notifications: self read"
  on notifications for select
  using (user_id = auth.uid());

-- Users can mark their own notifications as read
create policy "notifications: self update"
  on notifications for update
  using (user_id = auth.uid());

-- Inserts via service role

-- ---------------------------------------------------------------------------
-- ADMIN_ACTIONS
-- ---------------------------------------------------------------------------

alter table admin_actions enable row level security;

-- Admins can read the audit log
create policy "admin_actions: admin read"
  on admin_actions for select
  using (current_user_role() in ('admin', 'super_admin'));

-- Super admins can write (admins cannot write their own audit entries)
create policy "admin_actions: super_admin write"
  on admin_actions for insert
  with check (current_user_role() = 'super_admin');

-- No updates or deletes — append-only

-- ---------------------------------------------------------------------------
-- TRADES
-- ---------------------------------------------------------------------------

alter table trades enable row level security;

-- Parties to the trade can read it
create policy "trades: parties read"
  on trades for select
  using (initiator_id = auth.uid() or recipient_id = auth.uid());

-- Parties can update trades they're part of (status transitions enforced at app layer)
create policy "trades: parties update"
  on trades for update
  using (initiator_id = auth.uid() or recipient_id = auth.uid());

-- Initiator creates the trade
create policy "trades: initiator insert"
  on trades for insert
  with check (initiator_id = auth.uid());

-- Admins can read all trades
create policy "trades: admin read"
  on trades for select
  using (current_user_role() in ('admin', 'super_admin'));

-- ---------------------------------------------------------------------------
-- TRADE_PACKAGES
-- ---------------------------------------------------------------------------

alter table trade_packages enable row level security;

-- Readable by trade parties
create policy "trade_packages: parties read"
  on trade_packages for select
  using (
    exists (
      select 1 from trades t
      where t.id = trade_packages.trade_id
        and (t.initiator_id = auth.uid() or t.recipient_id = auth.uid())
    )
  );

-- Writable by trade parties (adding/modifying their package)
create policy "trade_packages: parties write"
  on trade_packages for all
  using (
    exists (
      select 1 from trades t
      where t.id = trade_packages.trade_id
        and (t.initiator_id = auth.uid() or t.recipient_id = auth.uid())
    )
  );

-- ---------------------------------------------------------------------------
-- TRADE_PROPOSALS
-- ---------------------------------------------------------------------------

alter table trade_proposals enable row level security;

-- Readable by trade parties
create policy "trade_proposals: parties read"
  on trade_proposals for select
  using (
    exists (
      select 1 from trades t
      where t.id = trade_proposals.trade_id
        and (t.initiator_id = auth.uid() or t.recipient_id = auth.uid())
    )
  );

-- Either party can insert a proposal
create policy "trade_proposals: parties insert"
  on trade_proposals for insert
  with check (
    proposed_by = auth.uid()
    and exists (
      select 1 from trades t
      where t.id = trade_proposals.trade_id
        and (t.initiator_id = auth.uid() or t.recipient_id = auth.uid())
    )
  );

-- No updates — proposals are immutable once created

-- ---------------------------------------------------------------------------
-- PROVENANCE_RECORDS
-- ---------------------------------------------------------------------------

alter table provenance_records enable row level security;

-- Current owner can read provenance of their artworks
create policy "provenance_records: owner read"
  on provenance_records for select
  using (owner_user_id = auth.uid());

-- Previous owner can read too (transparency)
create policy "provenance_records: previous owner read"
  on provenance_records for select
  using (previous_owner_user_id = auth.uid());

-- Written by service role only — no user insert

-- Admins can read all provenance records
create policy "provenance_records: admin read"
  on provenance_records for select
  using (current_user_role() in ('admin', 'super_admin'));

-- ============================================================
-- 20260414000002_credit_cap_enforcement.sql
-- ============================================================

-- =============================================================================
-- Membership Credit Cap Enforcement
--
-- Two business rules enforced as a single BEFORE INSERT trigger:
--
-- 1. founding_member credit
--    - Issued exactly once per user (no duplicate grants)
--    - months_credited must be exactly 3
--
-- 2. referral_bonus credit
--    - Sum of months_credited across all referral_bonus rows for a user
--      may not exceed 3 (i.e. at most 3 referral months total)
--
-- The trigger is the authoritative guard. Application code should pre-check
-- and show a user-facing message, but the trigger fires regardless of which
-- code path writes the row.
-- =============================================================================

create or replace function enforce_membership_credit_rules()
returns trigger
language plpgsql
as $$
declare
  existing_count   integer;
  existing_months  integer;
begin

  -- -------------------------------------------------------------------------
  -- Rule 1: founding_member — issued once, exactly 3 months
  -- -------------------------------------------------------------------------
  if new.credit_type = 'founding_member' then

    -- Reject if a founding_member row already exists for this user
    select count(*)
      into existing_count
      from membership_credits
     where user_id = new.user_id
       and credit_type = 'founding_member';

    if existing_count > 0 then
      raise exception
        'founding member credit already issued for user %',
        new.user_id
        using errcode = 'check_violation';
    end if;

    -- Reject if the grant is not exactly 3 months
    if new.months_credited <> 3 then
      raise exception
        'founding member credit must be exactly 3 months; got %',
        new.months_credited
        using errcode = 'check_violation';
    end if;

    return new;
  end if;

  -- -------------------------------------------------------------------------
  -- Rule 2: referral_bonus — sum may not exceed 3 months total
  -- -------------------------------------------------------------------------
  if new.credit_type = 'referral_bonus' then

    select coalesce(sum(months_credited), 0)
      into existing_months
      from membership_credits
     where user_id = new.user_id
       and credit_type = 'referral_bonus';

    if existing_months + new.months_credited > 3 then
      raise exception
        'referral credit cap exceeded: user % already has % referral month(s) credited; '
        'attempted to add %, cap is 3',
        new.user_id, existing_months, new.months_credited
        using errcode = 'check_violation';
    end if;

    return new;
  end if;

  -- Any future credit_type not handled above passes through
  return new;
end;
$$;

create trigger membership_credits_cap_enforcement
  before insert on membership_credits
  for each row execute function enforce_membership_credit_rules();

-- ============================================================
-- 20260414000003_add_trade_completion_credit_type.sql
-- ============================================================

-- =============================================================================
-- Add trade_completion to credit_type enum
--
-- Isolated in its own migration file because ALTER TYPE ... ADD VALUE cannot
-- be used in the same transaction as any statement that references the new
-- value. Running this in a separate file ensures the value is committed before
-- migration 000004 opens its transaction and updates the trigger function.
-- =============================================================================

alter type credit_type add value 'trade_completion';

-- ============================================================
-- 20260414000004_platform_settings_and_trade_credit_trigger.sql
-- ============================================================

-- =============================================================================
-- Migration 4: Platform Settings + trade_completion trigger update
--
-- Depends on 000003 having committed the trade_completion enum value before
-- this migration runs.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. PLATFORM_SETTINGS
--
-- Key-value store for runtime configuration that needs to be readable and
-- updatable without a schema migration. Suitable for feature flags and
-- enrollment windows. Not intended for secrets — use environment variables
-- for anything sensitive.
-- ---------------------------------------------------------------------------

create table platform_settings (
  key          varchar primary key,
  value        text not null,
  description  text,
  updated_at   timestamptz not null default now()
);

create trigger platform_settings_updated_at
  before update on platform_settings
  for each row execute function set_updated_at();

alter table platform_settings enable row level security;

-- Anyone authenticated can read settings (used for client-side feature flags)
create policy "platform_settings: authenticated read"
  on platform_settings for select
  to authenticated
  using (true);

-- Only admins can update settings
create policy "platform_settings: admin write"
  on platform_settings for all
  using (current_user_role() in ('admin', 'super_admin'));

-- Seed: founding member enrollment window
insert into platform_settings (key, value, description) values (
  'founding_member_enrollment_open',
  'true',
  'Controls whether new signups are granted founding member status and the associated 3-month credit. Set to false after the enrollment window closes.'
);

-- ---------------------------------------------------------------------------
-- 2. Update enforce_membership_credit_rules to explicitly handle
--    trade_completion — no cap, passes through unconditionally.
--
-- founding_member and referral_bonus rules are unchanged.
-- ---------------------------------------------------------------------------

create or replace function enforce_membership_credit_rules()
returns trigger
language plpgsql
as $$
declare
  existing_count   integer;
  existing_months  integer;
begin

  -- -------------------------------------------------------------------------
  -- Rule 1: founding_member — issued once, exactly 3 months
  -- -------------------------------------------------------------------------
  if new.credit_type = 'founding_member' then

    select count(*)
      into existing_count
      from membership_credits
     where user_id = new.user_id
       and credit_type = 'founding_member';

    if existing_count > 0 then
      raise exception
        'founding member credit already issued for user %',
        new.user_id
        using errcode = 'check_violation';
    end if;

    if new.months_credited <> 3 then
      raise exception
        'founding member credit must be exactly 3 months; got %',
        new.months_credited
        using errcode = 'check_violation';
    end if;

    return new;
  end if;

  -- -------------------------------------------------------------------------
  -- Rule 2: referral_bonus — sum may not exceed 3 months total
  -- -------------------------------------------------------------------------
  if new.credit_type = 'referral_bonus' then

    select coalesce(sum(months_credited), 0)
      into existing_months
      from membership_credits
     where user_id = new.user_id
       and credit_type = 'referral_bonus';

    if existing_months + new.months_credited > 3 then
      raise exception
        'referral credit cap exceeded: user % already has % referral month(s) credited; '
        'attempted to add %, cap is 3',
        new.user_id, existing_months, new.months_credited
        using errcode = 'check_violation';
    end if;

    return new;
  end if;

  -- -------------------------------------------------------------------------
  -- Rule 3: trade_completion — no cap, unlimited accrual
  -- One credit row per completed trade. Cap logic does not apply.
  -- -------------------------------------------------------------------------
  if new.credit_type = 'trade_completion' then
    return new;
  end if;

  -- Any future credit_type not handled above passes through
  return new;
end;
$$;

-- Trigger binding is unchanged — existing trigger picks up the replaced function automatically

-- ============================================================
-- 20260414000005_storage_buckets.sql
-- ============================================================

-- Create storage buckets (idempotent)
insert into storage.buckets (id, name, public)
values
  ('avatars',        'avatars',        true),
  ('artwork-photos', 'artwork-photos', true)
on conflict (id) do nothing;

-- Storage RLS: anyone can read public buckets
create policy "avatars: public read"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "avatars: owner upload"
  on storage.objects for insert
  with check (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "avatars: owner delete"
  on storage.objects for delete
  using (
    bucket_id = 'avatars'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "artwork-photos: public read"
  on storage.objects for select
  using (bucket_id = 'artwork-photos');

create policy "artwork-photos: owner upload"
  on storage.objects for insert
  with check (
    bucket_id = 'artwork-photos'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

create policy "artwork-photos: owner delete"
  on storage.objects for delete
  using (
    bucket_id = 'artwork-photos'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- ============================================================
-- 20260416000000_add_username.sql
-- ============================================================

-- =============================================================================
-- Add username column to users
-- Unique, indexed, required. Generated server-side during auth callback.
-- =============================================================================

alter table users
  add column username citext;

-- Backfill existing rows with a placeholder derived from id to satisfy NOT NULL
-- (safe because the column is newly added and no production users exist yet).
update users
  set username = 'user-' || substring(id::text from 1 for 8)
  where username is null;

alter table users
  alter column username set not null;

create unique index users_username_key on users (username);

-- ============================================================
-- 20260417000000_add_terms_accepted_at.sql
-- ============================================================

-- =============================================================================
-- Add terms_accepted_at column to users
-- Timestamp set when the user ticks the Terms + Privacy agreement on Step 1.
-- Nullable; existing rows keep null. Set once, never overwritten.
-- =============================================================================

alter table users
  add column terms_accepted_at timestamptz;

-- ============================================================
-- 20260420000000_add_is_test_user.sql
-- ============================================================

-- =============================================================================
-- Add is_test_user flag to users
-- Used by read queries (landing stats, discover, following, admin, etc.) to
-- filter out development test accounts seeded by the /dev/test-login utility.
-- Defaults to false; indexed for fast filtering on aggregate counts.
-- =============================================================================

alter table users
  add column is_test_user boolean not null default false;

-- Backfill: any rows whose email sits in the dev test domain get flagged.
update users
  set is_test_user = true
  where email ilike '%@test.ftae.local';

create index users_is_test_user_idx on users (is_test_user);

-- ============================================================
-- 20260421000000_add_photo_focal_point.sql
-- ============================================================

-- =============================================================================
-- Add focal point to artwork_photos
-- Fractions [0, 1] of the photo's natural dimensions marking where the subject
-- sits. Square thumbnail surfaces (Profile grid, Discover grid) render with
-- CSS `object-position: X% Y%` derived from these so the subject stays in
-- view instead of the geometric center being cropped.
-- =============================================================================

alter table artwork_photos
  add column focal_x real not null default 0.5,
  add column focal_y real not null default 0.5;

alter table artwork_photos
  add constraint artwork_photos_focal_x_range check (focal_x >= 0 and focal_x <= 1),
  add constraint artwork_photos_focal_y_range check (focal_y >= 0 and focal_y <= 1);

-- ============================================================
-- 20260421000001_drop_photo_type.sql
-- ============================================================

-- =============================================================================
-- Drop photo_type from artwork_photos
-- The column was scaffolded with enum values front/back/detail/shipping, but
-- assignments were position-based and the UI never surfaced the distinction.
-- Thumbnail selection now relies solely on sort_order (first photo wins).
-- =============================================================================

alter table artwork_photos drop column photo_type;

drop type artwork_photo_type;

-- ============================================================
-- 20260422000000_purge_stale_signups.sql
-- ============================================================

-- =============================================================================
-- Purge stale signups
--
-- A user who clicks the magic link triggers a row in `auth.users` plus a
-- public.users row. If they never accept the Terms + Privacy on Step 1
-- (terms_accepted_at remains null), we should not retain their email
-- indefinitely. After a 3-day grace window, the row is purged from both
-- public.users (cascading to dependent rows) and auth.users.
--
-- Implementation:
--   - SECURITY DEFINER function owned by `postgres` so it can touch auth.users.
--   - Scheduled daily via pg_cron.
--   - Idempotent — safe to run repeatedly.
--   - Users who accepted ToS at any point are never purged, regardless of
--     subsequent activity.
-- =============================================================================

create extension if not exists pg_cron with schema extensions;

create or replace function public.purge_stale_signups()
returns integer
language plpgsql
security definer
set search_path = public, extensions, auth
as $$
declare
  purged_count integer;
begin
  with purgees as (
    delete from public.users
    where terms_accepted_at is null
      and created_at < now() - interval '3 days'
    returning id
  ),
  auth_purge as (
    delete from auth.users
    where id in (select id from purgees)
    returning id
  )
  select count(*) into purged_count from auth_purge;

  return coalesce(purged_count, 0);
end;
$$;

revoke all on function public.purge_stale_signups() from public;

select cron.schedule(
  'purge-stale-signups-daily',
  '17 4 * * *',
  $$ select public.purge_stale_signups(); $$
);

-- ============================================================
-- 20260423000000_add_username_changed_at.sql
-- ============================================================

-- =============================================================================
-- Track the timestamp of the last successful username change.
-- NULL = the user has never explicitly changed their username via the
-- management flow. The first onboarding pick does NOT set this column, so
-- the user can still go to Edit Username after completing onboarding without
-- hitting the 30-day cooldown. Every successful change-via-magic-link sets
-- this to now(); the cooldown is enforced at >= 30 days from this timestamp.
-- =============================================================================

alter table users
  add column username_changed_at timestamptz;

-- ============================================================
-- 20260423000001_rls_explicit_denies.sql
-- ============================================================

-- =============================================================================
-- Defense-in-depth: explicit RLS deny policies on append-only tables.
--
-- Postgres RLS denies any operation that has no matching policy, so the
-- previous behavior was already locked down at runtime. The risk these
-- explicit denies guard against is a future migration that adds a permissive
-- `for all` or `for update` policy without realizing the table is meant to be
-- append-only — an explicit `using (false)` makes that intent visible and
-- forces anyone changing it to do so deliberately.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- MEMBERSHIP_CREDITS — append-only ledger.
-- ---------------------------------------------------------------------------

create policy "membership_credits: no update"
  on membership_credits for update
  using (false);

create policy "membership_credits: no delete"
  on membership_credits for delete
  using (false);

-- ---------------------------------------------------------------------------
-- TRADE_PROPOSALS — proposals are immutable once created.
-- ---------------------------------------------------------------------------

create policy "trade_proposals: no update"
  on trade_proposals for update
  using (false);

create policy "trade_proposals: no delete"
  on trade_proposals for delete
  using (false);

-- ---------------------------------------------------------------------------
-- ADMIN_ACTIONS — audit log is append-only.
-- ---------------------------------------------------------------------------

create policy "admin_actions: no update"
  on admin_actions for update
  using (false);

create policy "admin_actions: no delete"
  on admin_actions for delete
  using (false);

-- ---------------------------------------------------------------------------
-- MEDIUMS — canonical list managed via migrations only.
--
-- The original "mediums: admin write" policy used `for all`, which let
-- admins UPDATE/DELETE canonical rows from the app. Renaming or deleting a
-- medium would corrupt the discovery filter and break user_mediums FK
-- references. Replace with INSERT-only so admins can add new mediums but
-- not mutate the existing ones; renames/removals must go through a
-- migration with the FK churn handled deliberately.
-- ---------------------------------------------------------------------------

drop policy if exists "mediums: admin write" on mediums;

create policy "mediums: admin insert"
  on mediums for insert
  with check (current_user_role() in ('admin', 'super_admin'));

create policy "mediums: no update"
  on mediums for update
  using (false);

create policy "mediums: no delete"
  on mediums for delete
  using (false);
